/*
Developed By: Alfred Kam (www.cs.mcgill.ca/~akam2/), McGill MCB
Supervisors: Jerome Waldispuhl and Mathieu Blanchette, McGill University
Type: Desktop / Tablet / Mobile Browser Edition
Supported Platforms: Android, iPod, iPhone, iPad, Chrome, Safari, FireFox
About: A McGill Phylo Project - Menu Control

Copyright Alfred Kam and McGill MCB

Version 0.5.9.1
Last Updated Nov 2011
*/
var DEV=!0,fix=!1,mobileDEBUG=!1;window.language=[["English","en"],["French","fr"]];
(function(){(function(){function d(){}d.prototype.theme=function(){$(".menu").removeClass("menu");$(".nav").removeClass("nav");$("#menu").addClass("tabletMenu");$("#menu").children().each(function(){$(this).addClass("tabletNav")});$("#log").removeClass("tabletNav");$("#log").css("fontSize","150%");for(var b=window.setHref,a=0;a<b.length;a++){var c=a<window.color.length?window.color[a]:window.color[a-window.color.length];$("#"+b[a][1]).html("<pre class='tabletNavBorder' style='background-color:"+c+
"'></pre><p class='tabletNavContent'>"+b[a][0]+"</p>");$("#"+b[a][1]).mouseover(function(){var a=document.getElementById(this.id),b=a.getElementsByTagName("pre")[0],a=a.getElementsByTagName("p")[0];a.style.backgroundColor=b.style.backgroundColor;a.className+=" addBorder-tablet";b.style.backgroundColor=""});$("#"+b[a][1]).mouseout(function(){var a=document.getElementById(this.id),b=a.getElementsByTagName("pre")[0],a=a.getElementsByTagName("p")[0];b.style.backgroundColor=a.style.backgroundColor;a.style.backgroundColor=
"";a.className=$.trim(a.className.replace(/addBorder-tablet/,""))});$("#"+b[a][1]).click(function(){window.location.hash=this.id;mcb.changePage(this.id);var a=document.getElementById(this.id),b=a.getElementsByTagName("pre")[0],a=a.getElementsByTagName("p")[0];if(""==b.style.backgroundColor)$("nav").children().each(function(){if("tools"!=this.id){var a=document.getElementById(this.id),b=a.getElementsByTagName("pre")[0],c=a.getElementsByTagName("p")[0];c.className=$.trim(c.className.replace(/addBorder-tablet/,
""));if(""==b.style.backgroundColor)b.style.backgroundColor=c.style.backgroundColor,c.style.backgroundColor="",$(this).mouseover(function(){c.style.backgroundColor=b.style.backgroundColor;c.className+=" addBorder-tablet";b.style.backgroundColor=""}),$(this).mouseout(function(){b.style.backgroundColor=c.style.backgroundColor;c.style.backgroundColor="";c.className=$.trim(c.className.replace(/addBorder-tablet/,""))})}}),$(this).unbind("mouseover"),$(this).unbind("mouseout"),a.style.backgroundColor=b.style.backgroundColor,
a.className+=" addBorder-tablet",b.style.backgroundColor=""})}};d.prototype.adjust=function(b){var a=this;window.innerWidth>window.innerHeight&&!0==b^void 0==b?($(".tabletMenu").css("width",window.innerWidth+"px"),b=!1,$("#log").css("right","2em")):window.innerHeight>window.innerWidth&&!1==b^void 0==b&&($(".tabletMenu").css("width",window.innerWidth+"px"),b=!0,$("#log").css("right",".2em"));window.setTimeout(function(){a.adjust(b)},1E3)};d.prototype.hasIncident=function(){for(var b=mcb.hash(),a=0;a<
window.setHref.length;a++)if(b.match(window.setHref[a][1])){b=window.setHref[a][1];$("#"+b).unbind("mouseover");$("#"+b).unbind("mouseout");var a=document.getElementById(b).getElementsByTagName("pre")[0],c=document.getElementById(b).getElementsByTagName("p")[0];c.style.backgroundColor=a.style.backgroundColor;c.className+=" addBorder-tablet";a.style.backgroundColor="";mcb.changePage(b);return}mcb.changePage(b.replace(/#/,""))};common.exportSingleton("tablet",d,[["theme",d.prototype.theme]])})();(function(){function d(){}
d.prototype.theme=function(){$("#log").addClass("desktopLog");for(var b=window.setHref,a=0;a<b.length;a++){var c=a<window.color.length?window.color[a]:window.color[a-window.color.length];$("#"+b[a][1]).html("<pre class='navBorder' style='background-color:"+c+"'></pre><p class='navContent'>"+b[a][0]+"</p>");$("#"+b[a][1]).mouseover(function(){var a=document.getElementById(this.id),b=a.getElementsByTagName("pre")[0],a=a.getElementsByTagName("p")[0];a.style.backgroundColor=b.style.backgroundColor;a.className+=
" addBorder";b.style.backgroundColor=""});$("#"+b[a][1]).mouseout(function(){var a=document.getElementById(this.id),b=a.getElementsByTagName("pre")[0],a=a.getElementsByTagName("p")[0];b.style.backgroundColor=a.style.backgroundColor;a.className=$.trim(a.className.replace(/addBorder/,""));a.style.backgroundColor=""});$("#"+b[a][1]).click(function(){window.location.hash=this.id;mcb.changePage(this.id);var a=document.getElementById(this.id),b=a.getElementsByTagName("pre")[0],a=a.getElementsByTagName("p")[0];
if(""==b.style.backgroundColor)$("nav").children().children().each(function(){console.log(this.id);if("tools"!=this.id){var a=document.getElementById(this.id),b=a.getElementsByTagName("pre")[0],c=a.getElementsByTagName("p")[0];c.className=$.trim(c.className.replace(/addBorder/,""));if(""==b.style.backgroundColor)b.style.backgroundColor=c.style.backgroundColor,c.style.backgroundColor="",$(this).mouseover(function(){c.style.backgroundColor=b.style.backgroundColor;b.style.backgroundColor="";c.className+=
" addBorder"}),$(this).mouseout(function(){b.style.backgroundColor=c.style.backgroundColor;c.style.backgroundColor="";c.className=$.trim(c.className.replace(/addBorder/,""))})}}),$(this).unbind("mouseover"),$(this).unbind("mouseout"),a.style.backgroundColor=b.style.backgroundColor,b.style.backgroundColor="",a.className+=" addBorder"})}};d.prototype.hasIncident=function(){for(var b=mcb.hash(),a=0;a<window.setHref.length;a++)if(b.match(window.setHref[a][1])){b=window.setHref[a][1];$("#"+b).unbind("mouseover");
$("#"+b).unbind("mouseout");var a=document.getElementById(b).getElementsByTagName("pre")[0],c=document.getElementById(b).getElementsByTagName("p")[0];c.style.backgroundColor=a.style.backgroundColor;a.style.backgroundColor="";c.className="navContent addBorder";mcb.changePage(b);return}mcb.changePage(b.replace(/#/,""))};common.exportSingleton("desktop",d,[["theme",d.prototype.theme]])})();(function(){function d(){}d.prototype.theme=function(){$("#tools").remove();$(".menu").removeClass("menu");$(".nav").removeClass("nav");
$("#menu").addClass("mobMenu");$("#menu").children().each(function(){$(this).addClass("mobNav")});var b=document,a=b.createElement("div"),c=this;a.id="mobBack";a.style.display="none";b.body.appendChild(a);$("#mobBack").html("<a href='#' id='back'>Back</a>");$("#mobBack").click(function(){$("#sandbox").html("");$("#menu").show("fast");footer.adjust("mobileMenu");c.adjust();$("#mobBack").hide();window.location.hash="#menu"});b=window.setHref;for(a=0;a<b.length;a++)$("#"+b[a][1]).css("backgroundColor",
window.color[a]),0==a%2?($("#"+b[a][1]).css("left","0.4em"),0==a?$("#"+b[a][1]).css("top","5em"):$("#"+b[a][1]).css("top","3em")):($("#"+b[a][1]).css("left",1.4*3.3+"em"),1==a?$("#"+b[a][1]).css("top","3.15em"):$("#"+b[a][1]).css("top","1.15em")),$("#"+b[a][1]).click(function(){$("#mobBack").show();$("#menu").hide();mcb.changePage(this.id);window.location.hash=this.id});$("#menu").append("<img src='http://phylo.cs.mcgill.ca/img/logo.png' class='mobImg'/>");$(".mobImg").css("left","2em");this.landscape=
!1;this.adjust()};d.prototype.adjust=function(){var b=this,a=window.setHref;if(window.innerWidth>window.innerHeight){if(!1==this.landscape){for(var c=0;c<a.length;c++)0==c%2?$("#"+a[c][1]).css("left","4em"):$("#"+a[c][1]).css("left","8.25em");$(".mobImg").css("left","9em");this.landscape=!0}}else if(!0==this.landscape){for(c=0;c<a.length;c++)0==c%2?$("#"+a[c][1]).css("left","0.4em"):$("#"+a[c][1]).css("left",1.4*3.3+"em");$(".mobImg").css("left","2em");this.landscape=!1}(""==$("#sandbox").html()||
""==document.getElementById("menu").style.display)&&window.setTimeout(function(){b.adjust()},1E3)};common.exportSingleton("mobile",d,[["theme",d.prototype.theme]])})();(function(){function d(){}d.prototype.theme=function(a){var b=a.createElement("footer");b.id="footer";b.style.width="400px";a.body.appendChild(b);$("#footer").html("<p class='footNote' style='padding-bottom: 2em;'> &#169; <a href='http://www.mcgill.ca/mcb/'>McGill MCB</a> & <a href='http://www.alfredkam.com'>Alfred Kam</a><br><span style='font-size:0.6em'><a href='http://crowdsource.cs.mcgill.ca/plugin/'>Want to contribute? Click Here</a></span><br><span style='font-size:0.6em'><a href='http://phylo.cs.mcgill.ca'>Go back to non-mobile edition</a></span></p>");
-1<window.location.pathname.search(/mini/)&&$("#miniNote").hide();$("#notWork").click(function(){window.location="http://phylo.cs.mcgill.ca/mini"})};d.prototype.adjust=function(a){console.log(a);"play"==a^"home"==a?(console.log("here"),"other"!=common.checkDevice()^"ipad"!=common.checkDevice()?$("#footer").hide():($("#footer").show(),$("#footer").css({position:"absolute",top:"35em"}),"other"!=common.checkDevice()&&"ipad"!=common.checkDevice()&&$("#phylo-footer").css({position:"relative",top:"11em"}))):
"menu"==a?$("#footer").css({position:"relative",top:"35em"}):"mobileMenu"==a?($("#footer").css({position:"absolute",top:"18em"}),$("#phylo-footer").css({position:"relative",top:"11em"})):(0>mcb.hash().search(/home/)&&$("#footer").hide(),$(".phylo-body").append("<footer id='#phylo-footer'>"+$("#footer").html()+"</footer>"),$("#phylo-footer").css({position:"relative",top:"35em"}))};var b=d.prototype;common.exportSingleton("footer",d,[["theme",b.theme],["adjust",b.adjust]])})();(function(){function d(){}
d.prototype.theme=function(b,a){for(var c=window.language,d="",e=0;e<c.length;e++)d=mcb.GET("lang")==c[e][1]?d+("<option selected='selected' value='"+c[e][1]+"'>"+c[e][0]+"</option>"):d+("<option value='"+c[e][1]+"'>"+c[e][0]+"</option>");$("#tools").append("<select class='lang' id='langopt'>"+d+"</selected>");"other"==common.checkDevice()?$("#langopt").css({left:"80%",top:"-2.85em"}):($("#langopt").css({left:"77%",top:"-2.4em"}),$("#log").css("top","-.2em"));$("#langopt").change(function(){$("#langopt option:selected").each(function(){mcb.cookie.erase("phyloLang");
mcb.cookie.create("phyloLang",$(this).val(),360);var b=a.location.search.replace(mcb.GET("lang"),$(this).val());a.location.search=b})})};common.exportSingleton("lang",d,[["theme",d.prototype.theme]])})();(function(){var d={desktop:function(b,a){window.option=window.mobileDEBUG?!1:!0;footer.theme(b,a);desktop.theme();footer.adjust("menu");desktop.hasIncident();lang.theme(b,a);var c=function(){688<window.innerWidth&1473>window.innerWidth?($(".phylo-body").css({width:0.8*window.innerWidth,left:0.1*window.innerWidth}),
$(".menuSqueezer").css({width:"",left:""})):688>window.innerWidth?$(".phylo-body").css({left:"0"}):($(".phylo-body").css({left:(window.innerWidth-1178.4)/2,width:1178.4}),$(".menuSqueezer").css({width:1473,left:(window.innerWidth-1473)/2}))};c();window.onhashchange=c;$(window).resize(function(){c()});mcb.run("post-menu")},ipad:function(b,a){window.option=!0;footer.theme(b,a);tablet.theme();footer.adjust("menu");tablet.hasIncident();lang.theme(b,a);tablet.adjust();mcb.run("post-menu")},mobile:function(b,
a){window.option=!1;footer.theme(b,a);mobile.theme();footer.adjust("mobileMenu")},nokia:function(){window.option=!1;mobile.theme()}};$(document).ready(function(){if(void 0==mcb.GET("lang"))if(null==mcb.cookie.read("phyloLang")){if("ipad"==common.checkDevice()^"other"==common.checkDevice()){window.location="http://phylo.cs.mcgill.ca/mobile/splash.html"+window.location.hash;return}mcb.cookie.create("phyloLang","en",360);window.location.search="?lang=en"+window.location.hash}else mcb.cookie.create("phyloLang",
mcb.cookie.read("phyloLang",360)),window.location.search="?lang="+mcb.cookie.read("phyloLang")+window.location.hash;else{for(var b=window.language,a=!1,c=0;c<b.length;c++)b[c][1]==mcb.GET("lang")&&(a=!0);if(!a){window.location="http://phylo.cs.mcgill.ca/mobile/splash.html"+window.location.hash;return}null==mcb.cookie.read("phyloLang")&&mcb.cookie.create("phyloLang",mcb.GET("lang"),360)}if("other"==common.checkDevice()^"ipad"==common.checkDevice()&&""==mcb.hash())window.location.hash="#home";mcb.history();
mcb.data("0");window.setHref="en"==mcb.GET("lang")?[["Home","home"],["Tutorial","tutorial"],["About","about"],["Credits","contact"],["Ranking","ranking"]]:[["Acceuil","home"],["Tutoriel","tutoriel"],["A propos","about"],["Cr&eacute;dits","contact"],["Classement","ranking"]];"other"!=common.checkDevice()&&"ipad"!=common.checkDevice()&&(window.setHref.shift(),window.setHref.unshift(["Play","play"]),window.setHref.pop());var f={start:function(){window.color=["#71B2E2","darkOrchid","green","orange"];
var a=document,b=window,c=a.createElement("nav");c.id="menu";c.className="menu";a.body.appendChild(c);c=a.createElement("div");c.id="sandbox";a.body.appendChild(c);c=mcb.href(b.setHref,{className:"nav"});c+="<div id='tools'></div>";"other"==common.checkDevice()&&(c="<div class='menuSqueezer'>"+c+"</div>");$("#menu").html(c);"ipad"==common.checkDevice()?d.ipad(a,b):"other"==common.checkDevice()?d.desktop(a,b):"qt"==common.checkDevice()?d.nokia(a,b):d.mobile(a,b)}};void 0!=mcb.GET("pluginID")?$(document).ready(function(){var a=
document,b=a.createElement("div");b.id="blah";b.innerHTML="<h2>Entering Development Mode, Waiting for plugin to load...</h2>";a.body.appendChild(b);$.post("http://crowdsource.alfredkam.com/phpDB/scripts.php",{mode:6,pluginToken:mcb.GET("pluginID")},function(a){console.log(a);var b=document.createElement("script");b.src=a;b.type="text/javascript";document.body.appendChild(b);window.setTimeout(function(){$("#blah").remove();mcb.init();mcb.run("init");"other"==common.checkDevice()^"ipad"==common.checkDevice()&&
mcb.run("pre-menu");mcb.preFetch(window.setHref,f)},500)}).error(function(){})}):(mcb.init(),mcb.run("init"),"other"==common.checkDevice()^"ipad"==common.checkDevice()&&mcb.run("pre-menu"),mcb.preFetch(window.setHref,f))})})()})();
(function(){function d(){}d.prototype.lightbox=function(b,a){$(document).ready(function(){var c=document,d=window;if(void 0==document.getElementById("warning-lightbox")){var e=c.createElement("div");e.id="warning-lightbox";c.body.appendChild(e)}$("#warning-lightbox").html("<div id='warning-lightbox-shadow'></div><div id='warning-lightbox-content'><div id='warning-lightbox-content-body'></div><div id='warning-lightbox-content-options'></div></div>");$("#warning-lightbox").css({position:"absolute",
top:"0",left:"0",width:"100%",height:"100%"});$("#warning-lightbox-shadow").css({position:"absolute",top:"0px",left:"0px",width:window.innerWidth,height:window.innerHeight,"background-color":"black",opacity:"0.8",zIndex:"200"});$("#warning-lightbox-content").css({position:"absolute",top:0.21*d.innerHeight,left:0.275*d.innerWidth,height:0.25*d.innerHeight,width:0.4*d.innerWidth,zIndex:"201",backgroundColor:"#505050"});$("#warning-lightbox-content-body").css({position:"relative","text-align":"center",
top:"10%",left:"5%",width:"90%",height:"80%",color:"#FFFFFF"});$("#warning-lightbox-content-options").css({position:"relative",left:"5%",width:"90%"});$("#warning-lightbox-content-options").html("<a class='warning-opts' href='#' id='warning-okay'>Okay</a>");$("#warning-okay").click(function(){try{void 0!=a.okay&&a.okay()}catch(b){}$("#warning-lightbox").remove()});$(".warning-opts").css({"float":"left","margin-left":"5%",padding:"1px 1px 1px 1px",position:"relative",left:"40%",backgroundColor:"#000000"});
try{void 0!=a.cancel&&($("#warning-lightbox-content-options").append("<a class='warning-opts' href='#' id='warning-cancel'>Cancel</a>"),$("#warning-okay").css({left:"25%"}),$("#warning-cancel").css({"float":"left",left:"30%","margin-left":"40%",backgroundColor:"#000000",padding:"1px 1px 1px 1px"}),$("#warning-cancel").click(function(){a.cancel();$("#warning-lightbox").html("")}))}catch(g){}$("#warning-lightbox-content-body").html(b)})};common.exportSingleton("bug",d,[["lightbox",d.prototype.lightbox]])})();
(function(){function d(){this.im=new Image;this.im.src="http://phylo.cs.mcgill.ca/img/loading15.gif";this.im.id="loading-gif"}d.prototype.install=function(){var a=this.im;if(void 0==document.getElementById("loading")){var b=document.createElement("div");b.id="loading";document.body.appendChild(b)}$("#loading").html("<div id='loading-box'></div>");document.getElementById("loading").appendChild(a);$("#loading-gif").css({position:"absolute",height:"40px",width:"200px",top:(window.innerHeight-40)/2,left:(window.innerWidth-
200)/2,zIndex:"250"});$("#loading-box").css({position:"absolute",height:window.innerHeight,width:window.innerWidth,"background-color":"#000000",opacity:"0.8",zIndex:"249",top:0,left:0})};d.prototype.uninstall=function(){$("#loading").html("")};var b=d.prototype;common.exportSingleton("loading",d,[["install",b.install],["uninstall",b.uninstall]])})();
(function(){function d(){}d.prototype.init=function(){var b=document,a=b.createElement("div");a.id="maintenance";b.body.appendChild(a);$("#maintenance").html("Oops! We are updating the site now. There may be glitches here and there!");$("body").css({"padding-top":"2em"});$("#maintenance").css({position:"absolute",top:"0px",left:"35%",fontSize:"95%",color:"white",backgroundColor:"cornflowerBlue"})};common.exportSingleton("maint",d,[["init",d.prototype.init]])})();
