/*
developed by: Kira Chu(www.cs.mcgill.ca/~cwu65).McGill MCB
supervisors: Jerome Waldispuhl, Mathieu Blanchette, McGill University
Type: Desktop/Tablet
Supported platform: Chrome, Safari, Firefox
About:Mcgill Phylo Project: Facebook, Local Database  User Connection

Copyright Chu Wu and McGill MCB
Version 0.0.2
Last Updated Sept 2011

*/
//sanbox author:kira chu 
(function(){function d(){}d.prototype.start=function(){function d(){if(document.getElementById("login")==void 0){var a=document.createElement("div");a.className="login";a.id="login";document.body.appendChild(a);document.getElementById("login").innerHTML=" <div id='fb-root'></div>\t<div id='connection' class='white_content'></div> <div id='fade' class='black_overlay'></div>";document.getElementById("connection").innerHTML="<ul id=connectS><li><div id='MCBlogin'></div><input id='lSubmit' class='sub'  type='submit' value='Login'></li><li><div id='MCBregister'></div><input id='rSubmit' class='sub' type='submit' value='Register'></li><li><span id='OO'>Or just sign in instantly with:</span><button id='faceB_login_B'></button></li></ul>";
$("#MCBlogin").html("<p id='screenT'></p> <form id='emaiLG' onsubmit='return false;'><ul> <li id='dU' class='descrip'>Username:</li> <li><input id='user_name' class='dInput' type='text' placeholder='nickname'></input></li> <li id='dP' class='descript'>Password:</li> <li><input id='pass_word' class='dInput' type='password' ></input></li></ul></form>");$("#MCBregister").html("<p id='screenT'></p> <form id='emaiLG' onsubmit='return false;'><ul> <li id='dU' class='descrip'>Username:</li> <li><input id='user_name' class='dInput' type='text' placeholder='nickname'></input></li> <li id='dP' class='descript'>Password:</li> <li><input id='pass_word' class='dInput' type='password' ></input></li><li class='descript'>Email Address(Optional)</li><li><input id='email' class='dInput' type='text' placeholder='Email Address' ></input></li></ul></form>");
c()}$(window).bind("resize",c);$("#rSubmit").click(function(){$("#MCBregister").html()==""?($("#MCBregister").html("<p id='screenT'></p> <form id='emaiLG' onsubmit='return false;'><ul> <li id='dU' class='descrip'>Username:</li> <li><input id='user_name' class='dInput' type='text' placeholder='nickname'></input></li> <li id='dP' class='descript'>Password:</li> <li><input id='pass_word' class='dInput' type='password' ></input></li><li class='descript'>Email Address(Optional)</li><li><input id='email' class='dInput' type='text' placeholder='Email Address' ></input></li></ul></form>"),
$("#screenT").html("REGISTRATION"),$("#MCBlogin").css("display")!="none"&&($("#MCBlogin").slideToggle(),$("#MCBlogin").html("")),$("#MCBregister").slideToggle(),$("#screenT").html("REGISTRATION"),$(".white_content").animate({height:"420px"},200),c()):(console.log("useranme "+$("#user_name").val()),$("#user_name").val()===""?$("#dU").css({color:"red"}):$("#dU").css("color","white"),$("#pass_word").val()===""?$("#dP").css({color:"red"}):$("#dP").css("color","white"),$("#pass_word").val()!=""&&$("#user_name").val()!=
""&&($("#dU").css({color:"white"}),$("#dP").css({color:"white"}),loading.install(),$.post("../phpdb/phyloDB2.php",{mode:6,user:$("#user_name").val(),pass:$("#pass_word").val(),email:$("#email").val()},function(b){loading.uninstall();b=="succ"?(window.guest=$("#user_name").val(),e("none"),$("#log").html("Log Out")):(bug.lightbox("Oops! Conflicting Username"),c())}).error(function(){loading.uninstall();bug.lightbox("Oops! We couldnt connect to the server.<br>We suspect you are not connected to the internet!");
c()})))});$("#lSubmit").click(function(){$("#MCBlogin").html()===""?($("#MCBlogin").html("<p id='screenT'></p> <form id='emaiLG' onsubmit='return false;'><ul> <li id='dU' class='descrip'>Username:</li> <li><input id='user_name' class='dInput' type='text' placeholder='nickname'></input></li> <li id='dP' class='descript'>Password:</li> <li><input id='pass_word' class='dInput' type='password' ></input></li></ul></form>"),$("#screenT").html("LOGIN"),$("#MCBregister").css("display")!="none"&&($("#MCBregister").slideToggle(),
$("#MCBregister").html("")),$("#MCBlogin").slideToggle(),$(".white_content").animate({height:"380px"},200),c()):(console.log("useranme"+$("#user_name").val()),$("#user_name").val()===""?$("#dU").css({color:"red"}):$("#dU").css({color:"white"}),$("#pass_word").val()===""?$("#dP").css({color:"red"}):$("#dP").css({color:"white"}),$("#pass_word").val()!=""&&$("#user_name").val()!=""&&($("#dU").css({color:"white"}),$("#dP").css({color:"white"}),loading.install(),$.post("../phpdb/phyloDB2.php",{mode:7,
user:$("#user_name").val(),pass:$("#pass_word").val()},function(b){loading.uninstall();console.log(b);b=="succ"?(window.guest=$("#username").val(),e("none"),$("#log").html("Log Out")):(bug.lightbox("Oops! Incorrect Credentials!"),c())}).error(function(){loading.uninstall();bug.lightbox("Oops! We couldnt connect to the server.<br>We suspect you are not connected to the internet!");c()})))})}function e(a){$(".black_overlay").css({display:a});$(".white_content").css({display:a});$("#MCBlogin").css({display:"none"}).html("");
$("#MCBregister").css({display:"none"}).html("");$(".white_content").animate({height:"200px"},200);c()}function c(){var a=$("#connection").css("width").replace("px",""),b=$("#connection").css("height").replace("px",""),a=($(window).width()-a)/2,b=($(window).height()-b)/2;a<50&&(a=50);b<50&&(b=50);$("#connection").css({top:b,left:a})}this.fbL=0;$(document).ready(function(){d();FB.init({appId:"143395669089424",status:!0,cookie:!0,xfbml:!0,oauth:!0});$("#faceB_login_B").click(function(){FB.login(function(a){a.authResponse?
(e("none"),$("login_LB_button").css({display:"none"}),console.log("Welcome!  Fetching your information.... "),FB.api("/me",function(b){console.log("Good to see you, "+b.name+".");this.fbL=1;var a=b.name;window.guest=b.name+"/"+b.id;console.log(b.local);$("#log").html("welcome:<span> "+a+"</span>")})):console.log("user cancel/doest not authorize facebook login")},{scope:"publish_actions,user_about_me"})});$("#log").click(function(){$(this).html()=="Log In"?(e("block"),$("#fade").click(function(){e("none")})):
(this.fbL===1&&FB.logout(function(){console.log("Logged out.")}),$(this).html("Log In"),window.guest="guest")})})};common.exportSingleton("login",d,[["init",d.prototype.start]])})();
