<?php
	#AUTOGENERATED BY HYBRIDAUTH 2.1.0 INSTALLER - Friday 9th of November 2012 05:01:44 PM

/*!
* HybridAuth
* http://hybridauth.sourceforge.net | http://github.com/hybridauth/hybridauth
* (c) 2009-2012, HybridAuth authors | http://hybridauth.sourceforge.net/licenses.html
*/

// ----------------------------------------------------------------------------------------
//	HybridAuth Config file: http://hybridauth.sourceforge.net/userguide/Configuration.html
// ----------------------------------------------------------------------------------------

return 
	array(
		"base_url" => "http://phylo.cs.mcgill.ca/phpdb/hybridauth/hybridauth/", 

		"providers" => array ( 
			// openid providers
			"OpenID" => array (
				"enabled" => true
			),

			"AOL"  => array ( 
				"enabled" => false 
			),

			"Yahoo" => array ( 
				"enabled" => false,
				"keys"    => array ( "id" => "", "secret" => "" )
			),

			"Google" => array ( 
				"enabled" => true,
				"keys"    => array ( "id" => "288622764823.apps.googleusercontent.com", "secret" => "kyCFnXIud9HPFingUm_OpYDC" )
			),

			"Facebook" => array ( 
				"enabled" => true,
				"keys"    => array ( "id" => "254079141380941", "secret" => "56e422ddc36a76201055b1aa2b6c5f22" )
			),

			"Twitter" => array ( 
				"enabled" => true,
				"keys"    => array ( "key" => "lFMoJtM3AGIDmRHN7CCHg", "secret" => "1SMzHOFJJtzTL3B3ufdKf1KOGp35KuePGMPvwCWQGI" ) 
			),

			// windows live
			"Live" => array ( 
				"enabled" => false,
				"keys"    => array ( "id" => "", "secret" => "" ) 
			),

			"MySpace" => array ( 
				"enabled" => false,
				"keys"    => array ( "key" => "", "secret" => "" ) 
			),

			"LinkedIn" => array ( 
				"enabled" => true,
				"keys"    => array ( "key" => "2mlx5hsomkps", "secret" => "gIkNmvUF9jnHPEb5" ) 
			),

			"Foursquare" => array (
				"enabled" => false,
				"keys"    => array ( "id" => "", "secret" => "" ) 
			),
		),

		// if you want to enable logging, set 'debug_mode' to true  then provide a writable file by the web server on "debug_file"
		"debug_mode" => false,

		"debug_file" => ""
	);
